    package Sublime_Management;


import java.awt.Image;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Marce
 */
public class ViewSelectorRef extends javax.swing.JFrame {

    /**
     * Creates new form ViewSelectorRef
     */
    
    public ViewSelectorRef() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarTablaSelector();
        Image image = new ImageIcon(getClass().getResource("/res/windowIcon.png")).getImage();
        this.setIconImage(image);
    }
    public void actualizarTablaSelector(){
        
//        String nombres[] = {"Ref","Nombre","Cantidad","PVP"};
//        DefaultTableModel tm = new DefaultTableModel(nombres, 0);
        DefaultTableModel tm = Manager.limpiarDefaultTableModel((DefaultTableModel) tbSelectorRef.getModel());
        Iterator<Producto> it =  Productos.getProductos().iterator();
        while(it.hasNext()){
            Producto aux = it.next();
            tm.addRow(aux.getDatos());
        }
        
        tbSelectorRef.setModel(tm);
    }
    public void actualizarTablaSelectorPorNombre(){
        
//        String nombres[] = {"Ref","Nombre","Cantidad","PVP"};
//        DefaultTableModel tm = new DefaultTableModel(nombres, 0);
        DefaultTableModel tm = Manager.limpiarDefaultTableModel((DefaultTableModel) tbSelectorRef.getModel());
        Iterator<Producto> it =  Manager.buscarProductoPorNombre(fldNombreSelector.getText()).iterator();
        while(it.hasNext()){
            Producto aux = it.next();
            tm.addRow(aux.getDatos());
        }
        
        tbSelectorRef.setModel(tm);
    }
    public void actualizarTablaSelectorPorReferencia(){
        
//        String nombres[] = {"Ref","Nombre","Cantidad","PVP"};
//        DefaultTableModel tm = new DefaultTableModel(nombres, 0);
        DefaultTableModel tm = Manager.limpiarDefaultTableModel((DefaultTableModel) tbSelectorRef.getModel());
        Producto aux = Productos.getProductoByReference(fldReferenciaSelector.getText());
        if(aux==null){
            
        }else{
            tm.addRow(aux.getDatos());
        }
        
        tbSelectorRef.setModel(tm);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnSeleccinarRef = new javax.swing.JButton();
        fldNombreSelector = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        fldReferenciaSelector = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSelectorRef = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Buscar por nombre:");

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnSeleccinarRef.setText("Seleccionar");
        btnSeleccinarRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccinarRefActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar por Ref");

        tbSelectorRef.setAutoCreateRowSorter(true);
        tbSelectorRef.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ref", "Nombre", "Unidades", "PVP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSelectorRef.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbSelectorRef.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbSelectorRef);
        if (tbSelectorRef.getColumnModel().getColumnCount() > 0) {
            tbSelectorRef.getColumnModel().getColumn(0).setResizable(false);
            tbSelectorRef.getColumnModel().getColumn(1).setResizable(false);
            tbSelectorRef.getColumnModel().getColumn(2).setResizable(false);
            tbSelectorRef.getColumnModel().getColumn(3).setResizable(false);
        }

        jToggleButton1.setText("Cargar Todos");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldNombreSelector, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldReferenciaSelector, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccinarRef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fldNombreSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2)
                    .addComponent(fldReferenciaSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(btnSeleccinarRef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setObjeto(ViewPrograma aux){
        this.aux = aux;
    }
    public void setPadre(int i){
        this.receptor = i;
    }
    private void btnSeleccinarRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccinarRefActionPerformed
        try {
            if (receptor == 1) {
                String ref = (String) tbSelectorRef.getModel().getValueAt(tbSelectorRef.getSelectedRow(), 1);
                aux.setRefCompra(ref);
                this.dispose();
            }
            if (receptor == 2) {
                String ref = (String) tbSelectorRef.getModel().getValueAt(tbSelectorRef.getSelectedRow(), 1);
                aux.setRefVenta(ref);
                
                String precioP = Productos.getProductoByReference2(ref).getPvp();
                aux.setPrecioVenta(precioP+" €");
                aux.setPrecioFinal();
                this.dispose();
            }

        } catch (java.lang.ArrayIndexOutOfBoundsException ex) {
        }
    }//GEN-LAST:event_btnSeleccinarRefActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        actualizarTablaSelectorPorNombre();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        actualizarTablaSelectorPorReferencia();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        actualizarTablaSelector();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSelectorRef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSelectorRef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSelectorRef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSelectorRef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSelectorRef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccinarRef;
    private javax.swing.JTextField fldNombreSelector;
    private javax.swing.JTextField fldReferenciaSelector;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tbSelectorRef;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel dtm;
    private ViewPrograma aux;
    private int receptor;
}
