/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sublime_Management;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.hibernate.util.JTAHelper;

/**
 *
 * @author Marce
 */
public class ViewSelectorCliente extends javax.swing.JFrame {
    public List<JTextField> tfList = new LinkedList<JTextField>();
    public static ViewPrograma ventanaPadreViewPrograma;
    public ViewSelectorCliente() {
        initComponents();
        setListeners();
        actualizarTablaClienteSelector();
        Image image = new ImageIcon(getClass().getResource("/res/windowIcon.png")).getImage();
        this.setIconImage(image);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbSelectorCliente = new javax.swing.JTable();
        btnSeleccionarCliente = new javax.swing.JButton();
        fldNomberSelectorCliente = new javax.swing.JTextField();
        fldApellidoSelectorCliente = new javax.swing.JTextField();
        fldDNISelectorCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLimpiarCamposSelectorCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbSelectorCliente.setAutoCreateRowSorter(true);
        tbSelectorCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre", "Apellido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSelectorCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbSelectorCliente);
        if (tbSelectorCliente.getColumnModel().getColumnCount() > 0) {
            tbSelectorCliente.getColumnModel().getColumn(0).setResizable(false);
            tbSelectorCliente.getColumnModel().getColumn(1).setResizable(false);
            tbSelectorCliente.getColumnModel().getColumn(2).setResizable(false);
        }

        btnSeleccionarCliente.setText("Seleccionar");
        btnSeleccionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("DNI");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        btnLimpiarCamposSelectorCliente.setText("Limpiar");
        btnLimpiarCamposSelectorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposSelectorClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeleccionarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fldApellidoSelectorCliente)
                    .addComponent(fldNomberSelectorCliente)
                    .addComponent(fldDNISelectorCliente)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnLimpiarCamposSelectorCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldDNISelectorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldNomberSelectorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldApellidoSelectorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarCamposSelectorCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(btnSeleccionarCliente)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setListeners(){
        
        tfList.add(fldDNISelectorCliente);
        tfList.add(fldApellidoSelectorCliente);
        tfList.add(fldNomberSelectorCliente);
        for(JTextField aux : tfList){
            aux.addKeyListener(new KeyListener() {
                @Override
                public void keyTyped(KeyEvent ke) {
                    actualizarTablaClienteSelector();
                }

                @Override
                public void keyPressed(KeyEvent ke) {
                }

                @Override
                public void keyReleased(KeyEvent ke) {
                }
            });
        }
    }
    private void btnSeleccionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarClienteActionPerformed
        try {
            String ref = (String) tbSelectorCliente.getModel().getValueAt(tbSelectorCliente.getSelectedRow(), 0);
            ventanaPadreViewPrograma.setDNIClienteEnVenta(ref);
            this.dispose();

        } catch (java.lang.ArrayIndexOutOfBoundsException ex) {
        }
    }//GEN-LAST:event_btnSeleccionarClienteActionPerformed

    private void btnLimpiarCamposSelectorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposSelectorClienteActionPerformed
        for(JTextField aux : tfList){
            aux.setText("");
        }
        actualizarTablaClienteSelector();
    }//GEN-LAST:event_btnLimpiarCamposSelectorClienteActionPerformed
    
    private void actualizarTablaClienteSelector(){
//        String cabezeras[] = {"DNI","Nombre","Apellido"};
//        DefaultTableModel dtm = new DefaultTableModel(cabezeras, 0);
        DefaultTableModel dtm = Manager.limpiarDefaultTableModel((DefaultTableModel) tbSelectorCliente.getModel());
        LinkedList<Cliente> clientes = Clientes.getClientes();
        String dni=fldDNISelectorCliente.getText().toLowerCase();
        String nombre=fldNomberSelectorCliente.getText().toLowerCase();
        String apellido=fldApellidoSelectorCliente.getText().toLowerCase();
        List<String[]> listaDatos = new LinkedList<String[]>();
        for(Cliente aux : clientes){
            
            if(aux.getDni().toLowerCase().matches(".*"+dni+".*")){
                if(aux.getNombre().toLowerCase().matches(".*"+nombre+".*")){
                    if(aux.getApellido().toLowerCase().matches(".*"+apellido+".*")){
                        String datos[] = new String[3];
                        datos[0]=aux.getDni();
                        datos[1]=aux.getNombre();
                        datos[2]=aux.getApellido();
                        listaDatos.add(datos);
                        
                    }
                }
            }
        }
        
        for (String[] aux : listaDatos){
            dtm.addRow(aux);
        }
        tbSelectorCliente.setModel(dtm);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSelectorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSelectorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSelectorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSelectorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSelectorCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiarCamposSelectorCliente;
    private javax.swing.JButton btnSeleccionarCliente;
    private javax.swing.JTextField fldApellidoSelectorCliente;
    private javax.swing.JTextField fldDNISelectorCliente;
    private javax.swing.JTextField fldNomberSelectorCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSelectorCliente;
    // End of variables declaration//GEN-END:variables
}
